<a href="https://colab.research.google.com/github/srilamaiti/ml_works/blob/main/MCRMSE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
from sklearn.metrics import mean_squared_error

In [3]:
def roundPartial(value, resolution):
    return round (value / resolution) * resolution



In [37]:
x = tf.constant([[1, 2, 4], [8, 16, 32], [1, 2, 3]])
a = tf.reduce_mean(x)  
print(tf.reduce_mean(x), tf.reduce_mean(x, 1), tf.reduce_mean(x, 0)  )

tf.Tensor(7, shape=(), dtype=int32) tf.Tensor([ 2 18  2], shape=(3,), dtype=int32) tf.Tensor([ 3  6 13], shape=(3,), dtype=int32)


In [44]:
x = tf.constant([[1., 1.], [2., 2.]])
tf.reduce_mean(x)  # 1.5
tf.reduce_mean(x, 0)  # [1.5, 1.5]
tf.reduce_mean(x, 1)  # [1.,  2.]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [53]:
import tensorflow as tf
def MCRMSE(y_true, y_pred):
    transform_pred = np.array(y_pred)
    for row, r in enumerate(y_pred):
        for col, c in enumerate(r):
            transform_pred[row,col] = roundPartial(c, .5)
    colwise_mse = tf.reduce_mean(tf.square(y_true - transform_pred), axis = 1)
    return tf.reduce_mean(tf.sqrt(colwise_mse), axis = -1, keepdims = True)

In [50]:
def MCRMSE_1(y_trues, y_preds):
    scores = []
    transform_pred = np.array(y_pred)
    for row, r in enumerate(y_pred):
        for col, c in enumerate(r):
            transform_pred[row,col] = roundPartial(c, .5)

    idxes = y_trues.shape[1]
    for i in range(idxes):
        y_true = y_trues[:, i]
        y_pred = transform_pred[:, i]
        score = (y_true - y_pred) ** 2
        scores.append(score)
    mcrmse_score = np.mean(np.sqrt(np.mean(scores)))
    return mcrmse_score, scores

In [25]:
y_true = np.array([[5, 4.5, 3.5], [2.5, 3, 3.5], [2, 2.5, 3]])
y_pred = np.array([[4.15, 3.58, 2.09], [2.578, 4.56, 2.99], [3.01, 3.54, 1.0008]])

In [49]:
transform = np.array(y_pred)
for row, r in enumerate(y_pred):
   for col, c in enumerate(r):
        transform[row,col] = roundPartial(c, .5)
transform

array([[4. , 3.5, 2. ],
       [2.5, 4.5, 3. ],
       [3. , 3.5, 1. ]])

In [54]:
MCRMSE(y_true, y_pred)#, MCRMSE_1(y_true, y_pred)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([1.17244085])>