<a href="https://colab.research.google.com/github/srilamaiti/ml_works/blob/main/stratified_sampling_testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import StratifiedShuffleSplit

In [27]:
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16], [17, 18], [19, 20]])
y = np.array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])
X

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [21]:
skf = StratifiedKFold(n_splits = 4, random_state = 1234, shuffle = True)
skf.get_n_splits(X, y)

print(skf)
for k_fold, (train_index, test_index) in enumerate(skf.split(X, y)):
    print(f"k fold : {k_fold + 1}")
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print("X_train")
    print(X_train)
    print("y_train")
    print(y_train)
    print("X_test")
    print(X_test)
    print("y_test")
    print(y_test)
    print("**********************************************")
    print("**********************************************")
    print()
    print()

StratifiedKFold(n_splits=4, random_state=1234, shuffle=True)
k fold : 1
TRAIN: [0 1 3 5 6 8 9] TEST: [2 4 7]
X_train
[[ 1  2]
 [ 3  4]
 [ 7  8]
 [11 12]
 [13 14]
 [17 18]
 [19 20]]
y_train
[0 1 1 1 0 0 1]
X_test
[[ 5  6]
 [ 9 10]
 [15 16]]
y_test
[0 0 1]
**********************************************
**********************************************


k fold : 2
TRAIN: [0 1 2 4 7 8 9] TEST: [3 5 6]
X_train
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 9 10]
 [15 16]
 [17 18]
 [19 20]]
y_train
[0 1 0 0 1 0 1]
X_test
[[ 7  8]
 [11 12]
 [13 14]]
y_test
[1 1 0]
**********************************************
**********************************************


k fold : 3
TRAIN: [0 2 3 4 5 6 7 9] TEST: [1 8]
X_train
[[ 1  2]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [19 20]]
y_train
[0 0 1 0 1 0 1 1]
X_test
[[ 3  4]
 [17 18]]
y_test
[1 0]
**********************************************
**********************************************


k fold : 4
TRAIN: [1 2 3 4 5 6 7 8] TEST: [0 9]
X_train
[[ 3  4]
 [ 5

In [28]:
sss = StratifiedShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
sss

StratifiedShuffleSplit(n_splits=5, random_state=0, test_size=0.2,
            train_size=None)

In [29]:
xtrain, xtest = list(sss.split(X, y))[0]

In [30]:
xtrain, xtest

(array([0, 3, 6, 9, 4, 1, 2, 5]), array([8, 7]))

In [31]:
sss = StratifiedShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
sss

StratifiedShuffleSplit(n_splits=5, random_state=0, test_size=0.2,
            train_size=None)

In [33]:
xtrain, xtest = list(sss.split(X, y))[0]
xtrain, xtest

(array([0, 3, 6, 9, 4, 1, 2, 5]), array([8, 7]))

In [35]:
for k in range(0,9):
    sss = StratifiedShuffleSplit(n_splits=5, test_size=0.2, random_state=k)
    xtrain, xtest = list(sss.split(X, y))[0]
    print(k,xtrain, xtest)

0 [0 3 6 9 4 1 2 5] [8 7]
1 [8 9 5 0 1 2 7 4] [3 6]
2 [1 9 3 4 5 6 8 2] [0 7]
3 [9 6 5 8 7 2 0 3] [4 1]
4 [5 9 8 0 7 3 2 6] [1 4]
5 [5 0 7 2 8 4 9 3] [1 6]
6 [9 6 7 0 1 3 2 8] [5 4]
7 [2 3 9 5 4 6 0 1] [7 8]
8 [1 0 2 4 9 7 3 8] [5 6]


In [48]:
splits = 5
from sklearn.utils import shuffle
tx = range(100)
ty = shuffle([0] * 50 + [1] * 50)

print(list(tx), ty)
from sklearn.model_selection import StratifiedShuffleSplit, StratifiedKFold
from sklearn import datasets

stratKfold = StratifiedKFold(n_splits=splits, shuffle=True, random_state=42)
shufflesplit = StratifiedShuffleSplit(n_splits=splits, random_state=42, test_size=2)

print("stratKFold")
for train_index, test_index in stratKfold.split(tx, ty):
    print("TRAIN:", train_index, "TEST:", test_index)
    print("*********************")

print("Shuffle Split")
for train_index, test_index in shufflesplit.split(tx, ty):
    print("TRAIN:", train_index, "TEST:", test_index)
    print("*********************")

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99] [0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1]
stratKFold
TRAIN: [ 0  1  2  3  4  6  7  8  9 10 11 12 13 14 15 16 17 19 21 24 26 27 28 29
 30 31 32 33 34 36 38 39 40 41 43 44 45 46 47 48 49 50 51 52 54 55 56 57
 59 60 61 63 64 65 67 68 69 70 71 72 73 74 76 77 79 80 81 82 83 84 85 87
 88 90 92 93 94 95 97 98] TEST: [ 5 18 20 22 23 25 35 37 42 53 58 62 66

In [45]:
tx.index([train_index])

ValueError: ignored