<a href="https://colab.research.google.com/github/srilamaiti/ml_works/blob/main/stratified_sampling_testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
import numpy as np
import pandas as pd
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import StratifiedShuffleSplit

In [44]:
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16], [17, 18], [19, 20]])
y = np.array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])
X

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [45]:
skf = StratifiedKFold(n_splits = 4, random_state = 1234, shuffle = True)
skf.get_n_splits(X, y)

print(skf)
for k_fold, (train_index, test_index) in enumerate(skf.split(X, y)):
    print(f"k fold : {k_fold + 1}")
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print("X_train")
    print(X_train)
    print("y_train")
    print(y_train)
    print("X_test")
    print(X_test)
    print("y_test")
    print(y_test)
    print("**********************************************")
    print("**********************************************")
    print()
    print()

StratifiedKFold(n_splits=4, random_state=1234, shuffle=True)
k fold : 1
TRAIN: [0 1 3 5 6 8 9] TEST: [2 4 7]
X_train
[[ 1  2]
 [ 3  4]
 [ 7  8]
 [11 12]
 [13 14]
 [17 18]
 [19 20]]
y_train
[0 1 1 1 0 0 1]
X_test
[[ 5  6]
 [ 9 10]
 [15 16]]
y_test
[0 0 1]
**********************************************
**********************************************


k fold : 2
TRAIN: [0 1 2 4 7 8 9] TEST: [3 5 6]
X_train
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 9 10]
 [15 16]
 [17 18]
 [19 20]]
y_train
[0 1 0 0 1 0 1]
X_test
[[ 7  8]
 [11 12]
 [13 14]]
y_test
[1 1 0]
**********************************************
**********************************************


k fold : 3
TRAIN: [0 2 3 4 5 6 7 9] TEST: [1 8]
X_train
[[ 1  2]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [19 20]]
y_train
[0 0 1 0 1 0 1 1]
X_test
[[ 3  4]
 [17 18]]
y_test
[1 0]
**********************************************
**********************************************


k fold : 4
TRAIN: [1 2 3 4 5 6 7 8] TEST: [0 9]
X_train
[[ 3  4]
 [ 5

In [46]:
sss = StratifiedShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
sss

StratifiedShuffleSplit(n_splits=5, random_state=0, test_size=0.2,
            train_size=None)

In [47]:
xtrain, xtest = list(sss.split(X, y))[0]

In [48]:
xtrain, xtest

(array([0, 3, 6, 9, 4, 1, 2, 5]), array([8, 7]))

In [49]:
sss = StratifiedShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
sss

StratifiedShuffleSplit(n_splits=5, random_state=0, test_size=0.2,
            train_size=None)

In [50]:
xtrain, xtest = list(sss.split(X, y))[0]
xtrain, xtest

(array([0, 3, 6, 9, 4, 1, 2, 5]), array([8, 7]))

In [51]:
for k in range(0,9):
    sss = StratifiedShuffleSplit(n_splits=5, test_size=0.2, random_state=k)
    xtrain, xtest = list(sss.split(X, y))[0]
    print(k,xtrain, xtest)

0 [0 3 6 9 4 1 2 5] [8 7]
1 [8 9 5 0 1 2 7 4] [3 6]
2 [1 9 3 4 5 6 8 2] [0 7]
3 [9 6 5 8 7 2 0 3] [4 1]
4 [5 9 8 0 7 3 2 6] [1 4]
5 [5 0 7 2 8 4 9 3] [1 6]
6 [9 6 7 0 1 3 2 8] [5 4]
7 [2 3 9 5 4 6 0 1] [7 8]
8 [1 0 2 4 9 7 3 8] [5 6]


In [ ]:
from sklearn.model_selection import StratifiedShuffleSplit, StratifiedKFold
from sklearn import datasets
from sklearn.utils import shuffle

In [69]:
splits = 3

tx = range(10)
ty = shuffle([0] * 5 + [1] * 5)

stratKfold = StratifiedKFold(n_splits=splits, shuffle=True, random_state=42)
for train_index, test_index in stratKfold.split(tx, ty):
    print("TRAIN:", len(train_index), "TEST:", len(test_index))
    print(train_index)
    print(test_index)

TRAIN: 6 TEST: 4
[1 2 4 5 7 9]
[0 3 6 8]
TRAIN: 7 TEST: 3
[0 1 2 3 6 8 9]
[4 5 7]
TRAIN: 7 TEST: 3
[0 3 4 5 6 7 8]
[1 2 9]


In [88]:
tx = range(100)
ty = shuffle([0] * 50 + [1] * 50)
test_df = pd.DataFrame(np.stack((tx, ty), axis = 1))
test_df.columns =['id', 'label']
test_df

id  label
0    0      0
1    1      1
2    2      0
3    3      0
4    4      1
..  ..    ...
95  95      0
96  96      0
97  97      1
98  98      1
99  99      0

[100 rows x 2 columns]

In [89]:
splits = 3
tx = range(100)
ty = shuffle([0] * 50 + [1] * 50)
test_df = pd.DataFrame(np.stack((tx, ty), axis = 1))
test_df.columns =['id', 'label']
test_df

for kfold, (train_indices, validation_indices) in enumerate(StratifiedKFold(n_splits =  splits, 
                                                                                shuffle = True, 
                                                                                random_state = 1234
                                                                               ).split(test_df['label'].values.tolist(), 
                                                                                       test_df['label'].values.tolist()
                                                                                      )):
  
    print("TRAIN:", len(train_indices), "TEST:", len(validation_indices))
    print(train_indices)
    print(validation_indices)

TRAIN: 66 TEST: 34
[ 0  1  2  3  4  7  9 11 12 14 15 16 17 18 19 21 22 23 24 25 27 28 29 30
 31 33 34 38 40 41 42 43 45 46 47 50 52 53 54 55 56 57 60 63 66 73 74 76
 77 78 79 80 81 82 83 84 85 86 88 90 91 94 96 97 98 99]
[ 5  6  8 10 13 20 26 32 35 36 37 39 44 48 49 51 58 59 61 62 64 65 67 68
 69 70 71 72 75 87 89 92 93 95]
TRAIN: 67 TEST: 33
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 16 17 18 20 21 26 27 32 35 36
 37 39 40 41 44 45 47 48 49 51 52 54 55 56 57 58 59 60 61 62 64 65 66 67
 68 69 70 71 72 74 75 76 77 83 87 89 90 92 93 94 95 96 99]
[14 15 19 22 23 24 25 28 29 30 31 33 34 38 42 43 46 50 53 63 73 78 79 80
 81 82 84 85 86 88 91 97 98]
TRAIN: 67 TEST: 33
[ 5  6  8 10 13 14 15 19 20 22 23 24 25 26 28 29 30 31 32 33 34 35 36 37
 38 39 42 43 44 46 48 49 50 51 53 58 59 61 62 63 64 65 67 68 69 70 71 72
 73 75 78 79 80 81 82 84 85 86 87 88 89 91 92 93 95 97 98]
[ 0  1  2  3  4  7  9 11 12 16 17 18 21 27 40 41 45 47 52 54 55 56 57 60
 66 74 76 77 83 90 94 96 99]


In [52]:
splits = 3
from sklearn.utils import shuffle
tx = range(10)
ty = shuffle([0] * 5 + [1] * 5)

print(list(tx), ty)
from sklearn.model_selection import StratifiedShuffleSplit, StratifiedKFold
from sklearn import datasets

stratKfold = StratifiedKFold(n_splits=splits, shuffle=True, random_state=42)
shufflesplit = StratifiedShuffleSplit(n_splits=splits, random_state=42, test_size=2)

print("stratKFold")
for train_index, test_index in stratKfold.split(tx, ty):
    print("TRAIN:", len(train_index), "TEST:", len(test_index))
    print(train_index)
    print(test_index)
    #print(tx[train_index], ty[test_index])
    print("*********************")

print("Shuffle Split")
for train_index, test_index in shufflesplit.split(tx, ty):
    print("TRAIN:", len(train_index), "TEST:", len(test_index))
    #print(tx[train_index], ty[test_index])
    print(train_index)
    print(test_index)
    print("*********************")

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] [0, 1, 1, 0, 1, 0, 0, 0, 1, 1]
stratKFold
TRAIN: 6 TEST: 4
[1 3 4 5 7 9]
[0 2 6 8]
*********************
TRAIN: 7 TEST: 3
[0 1 2 3 6 8 9]
[4 5 7]
*********************
TRAIN: 7 TEST: 3
[0 2 4 5 6 7 8]
[1 3 9]
*********************
Shuffle Split
TRAIN: 8 TEST: 2
[8 7 3 0 2 1 4 5]
[6 9]
*********************
TRAIN: 8 TEST: 2
[4 0 6 9 7 1 3 2]
[8 5]
*********************
TRAIN: 8 TEST: 2
[3 5 1 2 7 8 9 0]
[6 4]
*********************


In [53]:
import pandas as pd
my_list = [(1,2,3), (4,5,6), (7,8,9), (10,11,12), (13,14,15), (16,17,18), (19,20,21), (22,23,24), (25,26,27), (28,29,30)]
test_df = pd.DataFrame(my_list)
test_df

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
4  13  14  15
5  16  17  18
6  19  20  21
7  22  23  24
8  25  26  27
9  28  29  30

In [54]:
my_idx_list = []
import random
while True:
    val = random.randrange(0,9)
    if val not in my_idx_list:
        my_idx_list.append(val)
        if len(my_idx_list) < 5:
            continue
        else:
            break
my_idx_list

[2, 0, 7, 1, 5]

In [55]:
test_df.iloc[my_idx_list]

0   1   2
2   7   8   9
0   1   2   3
7  22  23  24
1   4   5   6
5  16  17  18

In [56]:
random.randrange(1,3), np.round(random.uniform(.1, .5),1), np.round(random.uniform(.1, .3),1), np.round(random.uniform(.4, .6),1)

(2, 0.2, 0.3, 0.5)

In [57]:
pd.DataFrame([1,2,3,4]).T

0  1  2  3
0  1  2  3  4

In [58]:
pd.DataFrame({"B":[1,2,3,4]}).T


0  1  2  3
B  1  2  3  4

In [59]:
pd.DataFrame({"A":[1,2,3,4]}).T

0  1  2  3
A  1  2  3  4

In [60]:
pd.concat([pd.DataFrame({"A":[1,2,3,4]}).T, pd.DataFrame({"A":[1,2,3,4]}).T], axis = 1)

0  1  2  3  0  1  2  3
A  1  2  3  4  1  2  3  4

In [61]:
test_df = pd.DataFrame({"Model": "test_model", "epoch" : range(1,5), "kfold": range(1,5), "A":[1,2,3,4]})
test1_df = pd.DataFrame({"B":[1,2,3,4]})
test_df

Model  epoch  kfold  A
0  test_model      1      1  1
1  test_model      2      2  2
2  test_model      3      3  3
3  test_model      4      4  4

In [62]:
pd.concat([test_df, test1_df], axis = 1)

Model  epoch  kfold  A  B
0  test_model      1      1  1  1
1  test_model      2      2  2  2
2  test_model      3      3  3  3
3  test_model      4      4  4  4

In [63]:
class my_class:
    def __init__(self):
        print("Fun")
test_class = my_class()

Fun


In [64]:
dir(test_class)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__']