<a href="https://colab.research.google.com/github/srilamaiti/ml_works/blob/main/stratified_sampling_testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import StratifiedShuffleSplit

In [27]:
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16], [17, 18], [19, 20]])
y = np.array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])
X

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [21]:
skf = StratifiedKFold(n_splits = 4, random_state = 1234, shuffle = True)
skf.get_n_splits(X, y)

print(skf)
for k_fold, (train_index, test_index) in enumerate(skf.split(X, y)):
    print(f"k fold : {k_fold + 1}")
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print("X_train")
    print(X_train)
    print("y_train")
    print(y_train)
    print("X_test")
    print(X_test)
    print("y_test")
    print(y_test)
    print("**********************************************")
    print("**********************************************")
    print()
    print()

StratifiedKFold(n_splits=4, random_state=1234, shuffle=True)
k fold : 1
TRAIN: [0 1 3 5 6 8 9] TEST: [2 4 7]
X_train
[[ 1  2]
 [ 3  4]
 [ 7  8]
 [11 12]
 [13 14]
 [17 18]
 [19 20]]
y_train
[0 1 1 1 0 0 1]
X_test
[[ 5  6]
 [ 9 10]
 [15 16]]
y_test
[0 0 1]
**********************************************
**********************************************


k fold : 2
TRAIN: [0 1 2 4 7 8 9] TEST: [3 5 6]
X_train
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 9 10]
 [15 16]
 [17 18]
 [19 20]]
y_train
[0 1 0 0 1 0 1]
X_test
[[ 7  8]
 [11 12]
 [13 14]]
y_test
[1 1 0]
**********************************************
**********************************************


k fold : 3
TRAIN: [0 2 3 4 5 6 7 9] TEST: [1 8]
X_train
[[ 1  2]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [19 20]]
y_train
[0 0 1 0 1 0 1 1]
X_test
[[ 3  4]
 [17 18]]
y_test
[1 0]
**********************************************
**********************************************


k fold : 4
TRAIN: [1 2 3 4 5 6 7 8] TEST: [0 9]
X_train
[[ 3  4]
 [ 5

In [28]:
sss = StratifiedShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
sss

StratifiedShuffleSplit(n_splits=5, random_state=0, test_size=0.2,
            train_size=None)

In [29]:
xtrain, xtest = list(sss.split(X, y))[0]

In [30]:
xtrain, xtest

(array([0, 3, 6, 9, 4, 1, 2, 5]), array([8, 7]))

In [31]:
sss = StratifiedShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
sss

StratifiedShuffleSplit(n_splits=5, random_state=0, test_size=0.2,
            train_size=None)

In [33]:
xtrain, xtest = list(sss.split(X, y))[0]
xtrain, xtest

(array([0, 3, 6, 9, 4, 1, 2, 5]), array([8, 7]))

In [35]:
for k in range(0,9):
    sss = StratifiedShuffleSplit(n_splits=5, test_size=0.2, random_state=k)
    xtrain, xtest = list(sss.split(X, y))[0]
    print(k,xtrain, xtest)

0 [0 3 6 9 4 1 2 5] [8 7]
1 [8 9 5 0 1 2 7 4] [3 6]
2 [1 9 3 4 5 6 8 2] [0 7]
3 [9 6 5 8 7 2 0 3] [4 1]
4 [5 9 8 0 7 3 2 6] [1 4]
5 [5 0 7 2 8 4 9 3] [1 6]
6 [9 6 7 0 1 3 2 8] [5 4]
7 [2 3 9 5 4 6 0 1] [7 8]
8 [1 0 2 4 9 7 3 8] [5 6]


In [36]:
splits = 5

tx = range(10)
ty = [0] * 5 + [1] * 5

from sklearn.model_selection import StratifiedShuffleSplit, StratifiedKFold
from sklearn import datasets

stratKfold = StratifiedKFold(n_splits=splits, shuffle=True, random_state=42)
shufflesplit = StratifiedShuffleSplit(n_splits=splits, random_state=42, test_size=2)

print("stratKFold")
for train_index, test_index in stratKfold.split(tx, ty):
    print("TRAIN:", train_index, "TEST:", test_index)

print("Shuffle Split")
for train_index, test_index in shufflesplit.split(tx, ty):
    print("TRAIN:", train_index, "TEST:", test_index)

stratKFold
TRAIN: [0 1 2 4 5 6 7 9] TEST: [3 8]
TRAIN: [1 2 3 4 5 7 8 9] TEST: [0 6]
TRAIN: [0 1 3 4 5 6 8 9] TEST: [2 7]
TRAIN: [0 1 2 3 6 7 8 9] TEST: [4 5]
TRAIN: [0 2 3 4 5 6 7 8] TEST: [1 9]
Shuffle Split
TRAIN: [8 4 1 0 6 5 7 2] TEST: [3 9]
TRAIN: [7 0 3 9 4 5 1 6] TEST: [8 2]
TRAIN: [1 2 5 6 4 8 9 0] TEST: [3 7]
TRAIN: [4 6 7 8 3 5 1 2] TEST: [9 0]
TRAIN: [7 2 6 5 4 3 0 9] TEST: [1 8]
