<a href="https://colab.research.google.com/github/srilamaiti/ml_works/blob/main/stratified_sampling_testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import StratifiedShuffleSplit

In [2]:
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13, 14], [15, 16], [17, 18], [19, 20]])
y = np.array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])
X

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [3]:
skf = StratifiedKFold(n_splits = 4, random_state = 1234, shuffle = True)
skf.get_n_splits(X, y)

print(skf)
for k_fold, (train_index, test_index) in enumerate(skf.split(X, y)):
    print(f"k fold : {k_fold + 1}")
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print("X_train")
    print(X_train)
    print("y_train")
    print(y_train)
    print("X_test")
    print(X_test)
    print("y_test")
    print(y_test)
    print("**********************************************")
    print("**********************************************")
    print()
    print()

StratifiedKFold(n_splits=4, random_state=1234, shuffle=True)
k fold : 1
TRAIN: [0 1 3 5 6 8 9] TEST: [2 4 7]
X_train
[[ 1  2]
 [ 3  4]
 [ 7  8]
 [11 12]
 [13 14]
 [17 18]
 [19 20]]
y_train
[0 1 1 1 0 0 1]
X_test
[[ 5  6]
 [ 9 10]
 [15 16]]
y_test
[0 0 1]
**********************************************
**********************************************


k fold : 2
TRAIN: [0 1 2 4 7 8 9] TEST: [3 5 6]
X_train
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 9 10]
 [15 16]
 [17 18]
 [19 20]]
y_train
[0 1 0 0 1 0 1]
X_test
[[ 7  8]
 [11 12]
 [13 14]]
y_test
[1 1 0]
**********************************************
**********************************************


k fold : 3
TRAIN: [0 2 3 4 5 6 7 9] TEST: [1 8]
X_train
[[ 1  2]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [19 20]]
y_train
[0 0 1 0 1 0 1 1]
X_test
[[ 3  4]
 [17 18]]
y_test
[1 0]
**********************************************
**********************************************


k fold : 4
TRAIN: [1 2 3 4 5 6 7 8] TEST: [0 9]
X_train
[[ 3  4]
 [ 5

In [4]:
sss = StratifiedShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
sss

StratifiedShuffleSplit(n_splits=5, random_state=0, test_size=0.2,
            train_size=None)

In [5]:
xtrain, xtest = list(sss.split(X, y))[0]

In [6]:
xtrain, xtest

(array([0, 3, 6, 9, 4, 1, 2, 5]), array([8, 7]))

In [7]:
sss = StratifiedShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
sss

StratifiedShuffleSplit(n_splits=5, random_state=0, test_size=0.2,
            train_size=None)

In [8]:
xtrain, xtest = list(sss.split(X, y))[0]
xtrain, xtest

(array([0, 3, 6, 9, 4, 1, 2, 5]), array([8, 7]))

In [9]:
for k in range(0,9):
    sss = StratifiedShuffleSplit(n_splits=5, test_size=0.2, random_state=k)
    xtrain, xtest = list(sss.split(X, y))[0]
    print(k,xtrain, xtest)

0 [0 3 6 9 4 1 2 5] [8 7]
1 [8 9 5 0 1 2 7 4] [3 6]
2 [1 9 3 4 5 6 8 2] [0 7]
3 [9 6 5 8 7 2 0 3] [4 1]
4 [5 9 8 0 7 3 2 6] [1 4]
5 [5 0 7 2 8 4 9 3] [1 6]
6 [9 6 7 0 1 3 2 8] [5 4]
7 [2 3 9 5 4 6 0 1] [7 8]
8 [1 0 2 4 9 7 3 8] [5 6]


In [10]:
splits = 3
from sklearn.utils import shuffle
tx = range(10)
ty = shuffle([0] * 5 + [1] * 5)

print(list(tx), ty)
from sklearn.model_selection import StratifiedShuffleSplit, StratifiedKFold
from sklearn import datasets

stratKfold = StratifiedKFold(n_splits=splits, shuffle=True, random_state=42)
shufflesplit = StratifiedShuffleSplit(n_splits=splits, random_state=42, test_size=2)

print("stratKFold")
for train_index, test_index in stratKfold.split(tx, ty):
    print("TRAIN:", len(train_index), "TEST:", len(test_index))
    print(train_index)
    print(test_index)
    #print(tx[train_index], ty[test_index])
    print("*********************")

print("Shuffle Split")
for train_index, test_index in shufflesplit.split(tx, ty):
    print("TRAIN:", len(train_index), "TEST:", len(test_index))
    #print(tx[train_index], ty[test_index])
    print(train_index)
    print(test_index)
    print("*********************")

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] [1, 0, 1, 0, 0, 1, 1, 0, 0, 1]
stratKFold
TRAIN: 6 TEST: 4
[1 2 4 5 8 9]
[0 3 6 7]
*********************
TRAIN: 7 TEST: 3
[0 1 2 3 6 7 8]
[4 5 9]
*********************
TRAIN: 7 TEST: 3
[0 3 4 5 6 7 9]
[1 2 8]
*********************
Shuffle Split
TRAIN: 8 TEST: 2
[6 8 3 1 2 0 5 4]
[7 9]
*********************
TRAIN: 8 TEST: 2
[5 1 7 9 8 0 3 2]
[6 4]
*********************
TRAIN: 8 TEST: 2
[3 4 0 2 8 6 9 1]
[7 5]
*********************


In [11]:
import pandas as pd
my_list = [(1,2,3), (4,5,6), (7,8,9), (10,11,12), (13,14,15), (16,17,18), (19,20,21), (22,23,24), (25,26,27), (28,29,30)]
test_df = pd.DataFrame(my_list)
test_df

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
4  13  14  15
5  16  17  18
6  19  20  21
7  22  23  24
8  25  26  27
9  28  29  30

In [12]:
my_idx_list = []
import random
while True:
    val = random.randrange(0,9)
    if val not in my_idx_list:
        my_idx_list.append(val)
        if len(my_idx_list) < 5:
            continue
        else:
            break
my_idx_list

[0, 1, 2, 6, 8]

In [13]:
test_df.iloc[my_idx_list]

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
6  19  20  21
8  25  26  27

In [14]:
random.randrange(1,3), np.round(random.uniform(.1, .5),1), np.round(random.uniform(.1, .3),1), np.round(random.uniform(.4, .6),1)

(1, 0.3, 0.2, 0.5)

In [15]:
pd.DataFrame([1,2,3,4]).T

0  1  2  3
0  1  2  3  4

In [16]:
pd.DataFrame({"B":[1,2,3,4]}).T


0  1  2  3
B  1  2  3  4

In [17]:
pd.DataFrame({"A":[1,2,3,4]}).T

0  1  2  3
A  1  2  3  4

In [18]:
pd.concat([pd.DataFrame({"A":[1,2,3,4]}).T, pd.DataFrame({"A":[1,2,3,4]}).T], axis = 1)

0  1  2  3  0  1  2  3
A  1  2  3  4  1  2  3  4

In [25]:
test_df = pd.DataFrame({"Model": "test_model", "epoch" : range(1,5), "kfold": range(1,5), "A":[1,2,3,4]})
test1_df = pd.DataFrame({"B":[1,2,3,4]})
test_df

Model  epoch  kfold  A
0  test_model      1      1  1
1  test_model      2      2  2
2  test_model      3      3  3
3  test_model      4      4  4

In [26]:
pd.concat([test_df, test1_df], axis = 1)

Model  epoch  kfold  A  B
0  test_model      1      1  1  1
1  test_model      2      2  2  2
2  test_model      3      3  3  3
3  test_model      4      4  4  4

In [ ]:
pd.series([1,2,3])

In [21]:
class my_class:
    def __init__(self):
        print("Fun")
test_class = my_class()

Fun


In [22]:
dir(test_class)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__']